#version: '3.9'
#
#services:
#  fb_story_bot:
##    build: .                 #del on server
#    image: mybot:latest
#    container_name: fb_story_bot
#    ports:
#      - "20149:5000"
#    environment:
#      - PYTHONUNBUFFERED=1
#    restart: unless-stopped


version: '3.9'

services:
  fb_story_api:
#    build:
#      context: .
#      dockerfile: Dockerfile.api
    image: bot-relacje-facebook-playwrite_fb_story_api:latest
    container_name: fb_story_api
    ports:
      - "20149:5000"
    volumes:
      - /data/stories.db:/app/stories.db
      - /data/cookies:/data/cookies
      - /data/config.yaml:/app/config.yaml
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  fb_story_worker:
#    build:
#      context: .
#      dockerfile: Dockerfile.worker
    image: bot-relacje-facebook-playwrite_fb_story_worker:latest
    container_name: fb_story_worker
    volumes:
      - /data/stories.db:/app/stories.db
      - /data/cookies:/data/cookies
      - /data/config.yaml:/app/config.yaml
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped