version: '3.9'

services:
  fb_story_bot:
    image: mybot:latest
    container_name: fb_story_bot
    ports:
      - "20149:5000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped